inherit_gem:
  bunto: .rubocop.yml

AllCops:
  Exclude:
    - lib/bunto-admin/public/**/*
    - src/**/*
    - node_modules/**/*
    - Gemfile
    - bunto-admin.gemspec

Metrics/BlockLength:
  Enabled: false
