language: ruby
rvm: 2.2
before_install:
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/branding
  - chmod a+x script/build
  - chmod a+x script/cibuild
  - chmod a+x script/cibuild-node
  - chmod a+x script/cibuild-ruby
  - chmod a+x script/docs-server
  - chmod a+x script/fmt
  - chmod a+x script/release
  - chmod a+x script/server-frontend
  - chmod a+x script/test-server
  - nvm install 6
install: script/bootstrap
script: script/cibuild
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
sudo: false
env:
  matrix:
    - TEST_SUITE=node
    - TEST_SUITE=ruby
after_success:
  - npm run test:cover:CI
branches:
  only:
    - master
