environment:
  nodejs_version: "6"
  RACK_ENV: test
  BUNTO_LOG_LEVEL: warn
  RUBY_VERSION: 22
  matrix:
    - TEST_SUITE: node
    #- TEST_SUITE: ruby

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - gem install bundler --no-ri --no-rdoc --version '1.13.7'
  - bundle config --local path vendor/bundle
  - sh script/bootstrap

build: off

branches:
  only:
    - master

before_test:
  - node --version
  - npm --version
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - sh script/cibuild

cache:
  - vendor/bundle
  - node_modules

init:
  - git config --global core.autocrlf true
